export const BoatData = [
  {
    id: "1",
    Name: "ALFA'S",
    CardImage: "/images/boats/ALFA'S/1.jpg",
    location: "İstanbul",
    url: "alfas",
    DetailImages: [
      "/images/boats/ALFA'S/1.jpg",
      "/images/boats/ALFA'S/2.jpg",
      "/images/boats/ALFA'S/3.jpg",
      "/images/boats/ALFA'S/4.jpg",
      "/images/boats/ALFA'S/5.jpg",
      "/images/boats/ALFA'S/6.jpg",
    ],
  },
  {
    id: "2",
    Name: "ATA BORA",
    CardImage: "/images/boats/ATA-BORA/1.jpg",
    location: "İstanbul",
    url: "ata-bora",
    DetailImages: [
      "/images/boats/ATA-BORA/1.jpg",
      "/images/boats/ATA-BORA/2.jpg",
      "/images/boats/ATA-BORA/3.jpg",
      "/images/boats/ATA-BORA/4.jpg",
      "/images/boats/ATA-BORA/5.jpg",
      "/images/boats/ATA-BORA/6.jpg",
      "/images/boats/ATA-BORA/7.jpg",
      "/images/boats/ATA-BORA/8.jpg",
      "/images/boats/ATA-BORA/9.jpg",
      "/images/boats/ATA-BORA/10.jpg",
      "/images/boats/ATA-BORA/11.jpg",
    ],
  },
  {
    id: "3",
    Name: "BALTIK 2",
    CardImage: "/images/boats/BALTIK-2/1.jpg",
    location: "İstanbul",
    url: "baltik-2",
    DetailImages: [
      "/images/boats/BALTIK-2/1.jpg",
      "/images/boats/BALTIK-2/2.jpg",
      "/images/boats/BALTIK-2/3.jpg",
      "/images/boats/BALTIK-2/4.jpg",
      "/images/boats/BALTIK-2/5.jpg",
      "/images/boats/BALTIK-2/6.jpg",
      "/images/boats/BALTIK-2/7.jpg",
      "/images/boats/BALTIK-2/8.jpg",
      "/images/boats/BALTIK-2/9.jpg",
      "/images/boats/BALTIK-2/10.jpg",
      "/images/boats/BALTIK-2/11.jpg",
    ],
  },
  {
    id: "4",
    Name: "BELLA",
    CardImage: "/images/boats/BELLA/1.jpg",
    location: "İstanbul",
    url: "bella",
    DetailImages: [
      "/images/boats/BELLA/1.jpg",
      "/images/boats/BELLA/2.jpg",
      "/images/boats/BELLA/3.jpg",
      "/images/boats/BELLA/4.jpg",
      "/images/boats/BELLA/5.jpg",
      "/images/boats/BELLA/6.jpg",
      "/images/boats/BELLA/7.jpg",
      "/images/boats/BELLA/8.jpg",
      "/images/boats/BELLA/9.jpg",
      "/images/boats/BELLA/10.jpg",
    ],
  },
  {
    id: "5",
    Name: "BODRUM 1",
    CardImage: "/images/boats/BODRUM-1/1.jpg",
    location: "Muğla",
    url: "bodrum-1",
    DetailImages: [
      "/images/boats/BODRUM-1/1.jpg",
      "/images/boats/BODRUM-1/2.jpg",
      "/images/boats/BODRUM-1/3.jpg",
      "/images/boats/BODRUM-1/4.jpg",
      "/images/boats/BODRUM-1/5.jpg",
      "/images/boats/BODRUM-1/6.jpg",
      "/images/boats/BODRUM-1/7.jpg",
      "/images/boats/BODRUM-1/8.jpg",
      "/images/boats/BODRUM-1/9.jpg",
      "/images/boats/BODRUM-1/10.jpg",
      "/images/boats/BODRUM-1/11.jpg",
      "/images/boats/BODRUM-1/12.jpg",
      "/images/boats/BODRUM-1/13.jpg",
      "/images/boats/BODRUM-1/14.jpg",
      "/images/boats/BODRUM-1/15.jpg",
      "/images/boats/BODRUM-1/16.jpg",
      "/images/boats/BODRUM-1/17.jpg",
    ],
  },
  {
    id: "6",
    Name: "BODRUM 2 ",
    CardImage: "/images/boats/BODRUM-2/1.jpg",
    location: "Muğla",
    url: "bodrum-2",
    DetailImages: [
      "/images/boats/BODRUM-2/1.jpg",
      "/images/boats/BODRUM-2/2.jpg",
      "/images/boats/BODRUM-2/3.jpg",
      "/images/boats/BODRUM-2/4.jpg",
      "/images/boats/BODRUM-2/5.jpg",
      "/images/boats/BODRUM-2/6.jpg",
      "/images/boats/BODRUM-2/7.jpg",
      "/images/boats/BODRUM-2/8.jpg",
      "/images/boats/BODRUM-2/9.jpg",
      "/images/boats/BODRUM-2/10.jpg",
      "/images/boats/BODRUM-2/11.jpg",
      "/images/boats/BODRUM-2/12.jpg",
      "/images/boats/BODRUM-2/13.jpg",
      "/images/boats/BODRUM-2/14.jpg",
      "/images/boats/BODRUM-2/15.jpg",
      "/images/boats/BODRUM-2/16.jpg",
      "/images/boats/BODRUM-2/17.jpg",
    ],
  },
  {
    id: "7",
    Name: "BOĞAZ ÇOCUĞU",
    CardImage: "/images/boats/BOGAZ-COCUGU/1.jpg",
    location: "İstanbul",
    url: "bogaz-cocugu",
    DetailImages: [
      "/images/boats/BOGAZ-COCUGU/1.jpg",
      "/images/boats/BOGAZ-COCUGU/2.jpg",
      "/images/boats/BOGAZ-COCUGU/3.jpg",
      "/images/boats/BOGAZ-COCUGU/4.jpg",
      "/images/boats/BOGAZ-COCUGU/5.jpg",
      "/images/boats/BOGAZ-COCUGU/6.jpg",
      "/images/boats/BOGAZ-COCUGU/7.jpg",
      "/images/boats/BOGAZ-COCUGU/8.jpg",
      "/images/boats/BOGAZ-COCUGU/9.jpg",
      "/images/boats/BOGAZ-COCUGU/10.jpg",
    ],
  },
  {
    id: "8",
    Name: "CALIENTE",
    CardImage: "/images/boats/CALIENTE/1.jpg",
    location: "İstanbul",
    url: "caliente",
    DetailImages: [
      "/images/boats/CALIENTE/1.jpg",
      "/images/boats/CALIENTE/2.jpg",
      "/images/boats/CALIENTE/3.jpg",
      "/images/boats/CALIENTE/4.jpg",
      "/images/boats/CALIENTE/5.jpg",
    ],
  },
  {
    id: "9",
    Name: "FANTASY",
    CardImage: "/images/boats/FANTASY/1.jpg",
    location: "İstanbul",
    url: "fantasy",
    DetailImages: [
      "/images/boats/FANTASY/1.jpg",
      "/images/boats/FANTASY/2.jpg",
      "/images/boats/FANTASY/3.jpg",
      "/images/boats/FANTASY/4.jpg",
      "/images/boats/FANTASY/5.jpg",
      "/images/boats/FANTASY/6.jpg",
    ],
  },
  {
    id: "10",
    Name: "HYPNOS",
    CardImage: "/images/boats/HYPNOS/1.jpg",
    location: "İstanbul",
    url: "hypnos",
    DetailImages: [
      "/images/boats/HYPNOS/1.jpg",
      "/images/boats/HYPNOS/2.jpg",
      "/images/boats/HYPNOS/3.jpg",
      "/images/boats/HYPNOS/4.jpg",
      "/images/boats/HYPNOS/5.jpg",
      "/images/boats/HYPNOS/6.jpg",
    ],
  },
  {
    id: "11",
    Name: "KAREL",
    CardImage: "/images/boats/KAREL/1.jpg",
    location: "İstanbul",
    url: "karel",
    DetailImages: [
      "/images/boats/KAREL/1.jpg",
      "/images/boats/KAREL/2.jpg",
      "/images/boats/KAREL/3.jpg",
      "/images/boats/KAREL/4.jpg",
      "/images/boats/KAREL/5.jpg",
      "/images/boats/KAREL/6.jpg",
      "/images/boats/KAREL/7.jpg",
      "/images/boats/KAREL/8.jpg",
    ],
  },
  {
    id: "12",
    Name: "MELİS-K",
    CardImage: "/images/boats/MELIS-K/1.jpg",
    location: "İstanbul",
    url: "melis-k",
    DetailImages: [
      "/images/boats/MELIS-K/1.jpg",
      "/images/boats/MELIS-K/2.jpg",
      "/images/boats/MELIS-K/3.jpg",
      "/images/boats/MELIS-K/4.jpg",
      "/images/boats/MELIS-K/5.jpg",
      "/images/boats/MELIS-K/6.jpg",
      "/images/boats/MELIS-K/7.jpg",
      "/images/boats/MELIS-K/8.jpg",
    ],
  },
  {
    id: "13",
    Name: "MİLENİUM",
    CardImage: "/images/boats/MILENIUM/1.jpg",
    location: "İstanbul",
    url: "milenium",
    DetailImages: [
      "/images/boats/MILENIUM/1.jpg",
      "/images/boats/MILENIUM/2.jpg",
      "/images/boats/MILENIUM/3.jpg",
      "/images/boats/MILENIUM/4.jpg",
      "/images/boats/MILENIUM/5.jpg",
      "/images/boats/MILENIUM/6.jpg",
      "/images/boats/MILENIUM/7.jpg",
      "/images/boats/MILENIUM/8.jpg",
      "/images/boats/MILENIUM/9.jpg",
      "/images/boats/MILENIUM/10.jpg",
    ],
  },
  {
    id: "14",
    Name: "ON ROAD",
    CardImage: "/images/boats/ON-ROAD/1.jpg",
    location: "İstanbul",
    url: "on-road",
    DetailImages: [
      "/images/boats/ON-ROAD/1.jpg",
      "/images/boats/ON-ROAD/2.jpg",
      "/images/boats/ON-ROAD/3.jpg",
      "/images/boats/ON-ROAD/4.jpg",
      "/images/boats/ON-ROAD/5.jpg",
      "/images/boats/ON-ROAD/6.jpg",
      "/images/boats/ON-ROAD/7.jpg",
      "/images/boats/ON-ROAD/8.jpg",
      "/images/boats/ON-ROAD/9.jpg",
      "/images/boats/ON-ROAD/10.jpg",
    ],
  },
  {
    id: "15",
    Name: "ORIENT",
    CardImage: "/images/boats/ORIENT/1.jpg",
    location: "İstanbul",
    url: "orient",
    DetailImages: [
      "/images/boats/ORIENT/1.jpg",
      "/images/boats/ORIENT/2.jpg",
      "/images/boats/ORIENT/3.jpg",
      "/images/boats/ORIENT/4.jpg",
      "/images/boats/ORIENT/5.jpg",
      "/images/boats/ORIENT/6.jpg",
      "/images/boats/ORIENT/7.jpg",
      "/images/boats/ORIENT/8.jpg",
      "/images/boats/ORIENT/9.jpg",
      "/images/boats/ORIENT/10.jpg",
    ],
  },
  {
    id: "16",
    Name: "RIVER ",
    CardImage: "/images/boats/RIVER/1.jpg",
    location: "İstanbul",
    url: "river",
    DetailImages: [
      "/images/boats/RIVER/1.jpg",
      "/images/boats/RIVER/2.jpg",
      "/images/boats/RIVER/3.jpg",
      "/images/boats/RIVER/4.jpg",
    ],
  },
  {
    id: "17",
    Name: "SELAMET DAVUT",
    CardImage: "/images/boats/SELAMET-DAVUT/1.jpg",
    location: "İstanbul",
    url: "selamet-davut",
    DetailImages: [
      "/images/boats/SELAMET-DAVUT/1.jpg",
      "/images/boats/SELAMET-DAVUT/2.jpg",
      "/images/boats/SELAMET-DAVUT/3.jpg",
      "/images/boats/SELAMET-DAVUT/4.jpg",
      "/images/boats/SELAMET-DAVUT/5.jpg",
    ],
  },
  {
    id: "18",
    Name: "WHITE HORSE",
    CardImage: "/images/boats/WHITE-HORSE/1.jpg",
    location: "İstanbul",
    url: "white-horse",
    DetailImages: [
      "/images/boats/WHITE-HORSE/1.jpg",
      "/images/boats/WHITE-HORSE/2.jpg",
      "/images/boats/WHITE-HORSE/3.jpg",
      "/images/boats/WHITE-HORSE/4.jpg",
      "/images/boats/WHITE-HORSE/5.jpg",
      "/images/boats/WHITE-HORSE/6.jpg",
      "/images/boats/WHITE-HORSE/7.jpg",
      "/images/boats/WHITE-HORSE/8.jpg",
      "/images/boats/WHITE-HORSE/9.jpg",
    ],
  },
];
