export const BoatData = [
  {
    id: "1",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/1/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/1/1.jpeg",
      "/images/motoryatlar/1/2.jpeg",
      "/images/motoryatlar/1/3.jpeg",
      "/images/motoryatlar/1/4.jpeg",
      "/images/motoryatlar/1/5.jpeg",
      "/images/motoryatlar/1/6.jpeg",
      "/images/motoryatlar/1/7.jpeg",
      "/images/motoryatlar/1/8.jpeg",
      "/images/motoryatlar/1/9.jpeg",
    ],
  },
  {
    id: "2",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/2/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/2/1.jpeg",
      "/images/motoryatlar/2/2.jpeg",
      "/images/motoryatlar/2/3.jpeg",
      "/images/motoryatlar/2/4.jpeg",
      "/images/motoryatlar/2/5.jpeg",
      "/images/motoryatlar/2/6.jpeg",
      "/images/motoryatlar/2/7.jpeg",
      "/images/motoryatlar/2/8.jpeg",
      "/images/motoryatlar/2/9.jpeg",
      "/images/motoryatlar/2/10.jpeg",
      "/images/motoryatlar/2/11.jpeg",
      "/images/motoryatlar/2/12.jpeg",
      "/images/motoryatlar/2/13.jpeg",
      "/images/motoryatlar/2/14.jpeg",
      "/images/motoryatlar/2/15.jpeg",
      "/images/motoryatlar/2/16.jpeg",
      "/images/motoryatlar/2/17.jpeg",
      "/images/motoryatlar/2/18.jpeg",
    ],
  },
  {
    id: "3",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/3/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/3/1.jpeg",
      "/images/motoryatlar/3/2.jpeg",
      "/images/motoryatlar/3/3.jpeg",
      "/images/motoryatlar/3/4.jpeg",
      "/images/motoryatlar/3/5.jpeg",
      "/images/motoryatlar/3/6.jpeg",
      "/images/motoryatlar/3/7.jpeg",
    ],
  },
  {
    id: "4",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/4/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/4/1.jpeg",
      "/images/motoryatlar/4/2.jpeg",
      "/images/motoryatlar/4/3.jpeg",
      "/images/motoryatlar/4/4.jpeg",
      "/images/motoryatlar/4/5.jpeg",
      "/images/motoryatlar/4/6.jpeg",
      "/images/motoryatlar/4/7.jpeg",
    ],
  },
  {
    id: "5",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/5/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/5/1.jpeg",
      "/images/motoryatlar/5/2.jpeg",
      "/images/motoryatlar/5/3.jpeg",
      "/images/motoryatlar/5/4.jpeg",
      "/images/motoryatlar/5/5.jpeg",
      "/images/motoryatlar/5/6.jpeg",
      "/images/motoryatlar/5/7.jpeg",
    ],
  },
  {
    id: "6",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/6/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/6/1.jpeg",
      "/images/motoryatlar/6/2.jpeg",
      "/images/motoryatlar/6/3.jpeg",
      "/images/motoryatlar/6/4.jpeg",
      "/images/motoryatlar/6/5.jpeg",
      "/images/motoryatlar/6/6.jpeg",
    ],
  },
  {
    id: "7",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/7/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/2.jpeg",
      "/images/motoryatlar/7/3.jpeg",
      "/images/motoryatlar/7/4.jpeg",
      "/images/motoryatlar/7/5.jpeg",
      "/images/motoryatlar/7/6.jpeg",
      "/images/motoryatlar/7/7.jpeg",
      "/images/motoryatlar/7/8.jpeg",
    ],
  },
  {
    id: "8",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/8/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
      "/images/motoryatlar/7/1.jpeg",
    ],
  },
  {
    id: "9",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/9/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/9/1.jpeg",
      "/images/motoryatlar/9/2.jpeg",
      "/images/motoryatlar/9/3.jpeg",
      "/images/motoryatlar/9/4.jpeg",
      "/images/motoryatlar/9/5.jpeg",
      "/images/motoryatlar/9/6.jpeg",
    ],
  },
  {
    id: "10",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/10/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/10/1.jpeg",
      "/images/motoryatlar/10/2.jpeg",
      "/images/motoryatlar/10/3.jpeg",
      "/images/motoryatlar/10/4.jpeg",
      "/images/motoryatlar/10/5.jpeg",
    ],
  },
  {
    id: "11",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/11/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/11/1.jpeg",
      "/images/motoryatlar/11/2.jpeg",
      "/images/motoryatlar/11/3.jpeg",
      "/images/motoryatlar/11/4.jpeg",
      "/images/motoryatlar/11/5.jpeg",
      "/images/motoryatlar/11/6.jpeg",
    ],
  },
  {
    id: "12",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/12/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/motoryatlar/12/1.jpeg",
      "/images/motoryatlar/12/2.jpeg",
      "/images/motoryatlar/12/3.jpeg",
      "/images/motoryatlar/12/4.jpeg",
      "/images/motoryatlar/12/5.jpeg",
      "/images/motoryatlar/12/6.jpeg",
      "/images/motoryatlar/12/7.jpeg",
      "/images/motoryatlar/12/8.jpeg",
    ],
  },
  {
    id: "13",
    type: "invite-yacht",
    CardImage: "/images/davet-tekneleri/1/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/davet-tekneleri/1/1.jpeg",
      "/images/davet-tekneleri/1/2.jpeg",
      "/images/davet-tekneleri/1/3.jpeg",
      "/images/davet-tekneleri/1/4.jpeg",
      "/images/davet-tekneleri/1/5.jpeg",
      "/images/davet-tekneleri/1/6.jpeg",
      "/images/davet-tekneleri/1/7.jpeg",
      "/images/davet-tekneleri/1/8.jpeg",
      "/images/davet-tekneleri/1/9.jpeg",
      "/images/davet-tekneleri/1/10.jpeg",
    ],
  },
  {
    id: "14",
    type: "invite-yacht",
    CardImage: "/images/davet-tekneleri/2/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/davet-tekneleri/2/1.jpeg",
      "/images/davet-tekneleri/2/1.jpeg",
      "/images/davet-tekneleri/2/1.jpeg",
      "/images/davet-tekneleri/2/1.jpeg",
      "/images/davet-tekneleri/2/1.jpeg",
      "/images/davet-tekneleri/2/1.jpeg",
    ],
  },
  {
    id: "15",
    type: "invite-yacht",
    CardImage: "/images/davet-tekneleri/3/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/davet-tekneleri/3/1.jpeg",
      "/images/davet-tekneleri/3/2.jpeg",
      "/images/davet-tekneleri/3/3.jpeg",
      "/images/davet-tekneleri/3/4.jpeg",
      "/images/davet-tekneleri/3/5.jpeg",
      "/images/davet-tekneleri/3/6.jpeg",
      "/images/davet-tekneleri/3/7.jpeg",
      "/images/davet-tekneleri/3/8.jpeg",
    ],
  },
  {
    id: "16",
    type: "invite-yacht",
    CardImage: "/images/davet-tekneleri/4/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/davet-tekneleri/4/1.jpeg",
      "/images/davet-tekneleri/4/2.jpeg",
      "/images/davet-tekneleri/4/3.jpeg",
      "/images/davet-tekneleri/4/4.jpeg",
      "/images/davet-tekneleri/4/5.jpeg",
      "/images/davet-tekneleri/4/6.jpeg",
    ],
  },
  {
    id: "17",
    type: "invite-yacht",
    CardImage: "/images/davet-tekneleri/5/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/davet-tekneleri/5/1.jpeg",
      "/images/davet-tekneleri/5/2.jpeg",
      "/images/davet-tekneleri/5/3.jpeg",
      "/images/davet-tekneleri/5/4.jpeg",
      "/images/davet-tekneleri/5/5.jpeg",
      "/images/davet-tekneleri/5/6.jpeg",
      "/images/davet-tekneleri/5/7.jpeg",
      "/images/davet-tekneleri/5/8.jpeg",
    ],
  },
];
