export const BoatData = [
  {
    id: "1",
    type: "motoryacht",
    description:
      "Siyah renge sahip yatımız bu özelliği ile İstanbul Boğazı'nda ilk ve tek olma özelliği  taşımaktadır.15 kişiye kadar yat kiralama hizmeti verilmektedir.",
    height: "20",
    capacity: "15",
    food: "13",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/1/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/1/1.jpeg",
      "/images/yachts/motoryatlar/1/2.jpeg",
      "/images/yachts/motoryatlar/1/3.jpeg",
      "/images/yachts/motoryatlar/1/4.jpeg",
      "/images/yachts/motoryatlar/1/5.jpeg",
      "/images/yachts/motoryatlar/1/6.jpeg",
      "/images/yachts/motoryatlar/1/7.jpeg",
      "/images/yachts/motoryatlar/1/8.jpeg",
      "/images/yachts/motoryatlar/1/9.jpeg",
    ],
  },
  {
    id: "2",
    type: "motoryacht",
    description:
      "Güler yüzlü personel ve kendine has görünümü ile en iyi yat kiralama hizmetini bu yatımızda bulabilirsiniz.Maksimum 10 kişiye kadar hizmet verilebilmektedir.",
    height: "17",
    capacity: "10",
    food: "10",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/2/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/2/1.jpeg",
      "/images/yachts/motoryatlar/2/2.jpeg",
      "/images/yachts/motoryatlar/2/3.jpeg",
      "/images/yachts/motoryatlar/2/4.jpeg",
      "/images/yachts/motoryatlar/2/5.jpeg",
      "/images/yachts/motoryatlar/2/6.jpeg",
      "/images/yachts/motoryatlar/2/7.jpeg",
      "/images/yachts/motoryatlar/2/8.jpeg",
      "/images/yachts/motoryatlar/2/9.jpeg",
      "/images/yachts/motoryatlar/2/10.jpeg",
      "/images/yachts/motoryatlar/2/11.jpeg",
      "/images/yachts/motoryatlar/2/12.jpeg",
      "/images/yachts/motoryatlar/2/13.jpeg",
      "/images/yachts/motoryatlar/2/14.jpeg",
      "/images/yachts/motoryatlar/2/15.jpeg",
      "/images/yachts/motoryatlar/2/16.jpeg",
      "/images/yachts/motoryatlar/2/17.jpeg",
      "/images/yachts/motoryatlar/2/18.jpeg",
    ],
  },
  {
    id: "3",
    type: "motoryacht",
    description:
      "Çekirdek aileler için vazgeçilmez olan bu yatımızda 8 kişiye kadar hizmet verilmekte olup,evlilik teklifi gibi organizasyonlarınız için mükemmel bir seçenektir.",
    height: "15",
    capacity: "7",
    food: "6",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/3/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/3/1.jpeg",
      "/images/yachts/motoryatlar/3/2.jpeg",
      "/images/yachts/motoryatlar/3/3.jpeg",
      "/images/yachts/motoryatlar/3/4.jpeg",
      "/images/yachts/motoryatlar/3/5.jpeg",
      "/images/yachts/motoryatlar/3/6.jpeg",
      "/images/yachts/motoryatlar/3/7.jpeg",
    ],
  },
  {
    id: "4",
    type: "motoryacht",
    description:
      "Arkadaş grubunuzla ufak bir parti veya kaçamak düşünüyor iseniz bu yatımız tam size göre.8 kişi kapasiteli yatımız yatta doğum günü organizasyonlarınız için ilk sıralarda yer almaktadır.    ",
    height: "16",
    capacity: "12",
    food: "8",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/4/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/4/1.jpeg",
      "/images/yachts/motoryatlar/4/2.jpeg",
      "/images/yachts/motoryatlar/4/3.jpeg",
      "/images/yachts/motoryatlar/4/4.jpeg",
      "/images/yachts/motoryatlar/4/5.jpeg",
      "/images/yachts/motoryatlar/4/6.jpeg",
      "/images/yachts/motoryatlar/4/7.jpeg",
    ],
  },
  {
    id: "5",
    type: "motoryacht",
    description:
      "30 kişi kapasitesi ile her türlü organizasyona ev sahipliği yapan bu yatımız eşsiz görünümü ve ışıklandırması ile tüm dikkatleri üzerine çekmektedir.  ",
    height: "24",
    capacity: "25",
    food: "25",
    crew: "3",
    CardImage: "/images/yachts/motoryatlar/5/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/5/1.jpeg",
      "/images/yachts/motoryatlar/5/2.jpeg",
      "/images/yachts/motoryatlar/5/3.jpeg",
      "/images/yachts/motoryatlar/5/4.jpeg",
      "/images/yachts/motoryatlar/5/5.jpeg",
      "/images/yachts/motoryatlar/5/6.jpeg",
      "/images/yachts/motoryatlar/5/7.jpeg",
    ],
  },
  {
    id: "6",
    type: "motoryacht",
    description:
      "Mavi-Beyaz görünümü ile deniz ile mükemmel bir uyum yakalayan bu yatımızda 15 kişiye kadar yat kiralama hizmeti verilmektedir.",
    height: "19",
    capacity: "15",
    food: "12",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/6/1.jpg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/6/1.jpg",
      "/images/yachts/motoryatlar/6/2.jpg",
      "/images/yachts/motoryatlar/6/3.jpg",
      "/images/yachts/motoryatlar/6/4.jpg",
      "/images/yachts/motoryatlar/6/5.jpg",
      "/images/yachts/motoryatlar/6/6.jpg",
    ],
  },
  {
    id: "7",
    type: "motoryacht",
    description:
      "Profesyonel hizmet anlayışını kendine ilke edinen lüks yatımız ile 15 kişiye kadar bireysel ve kurumsal organizasyonlarınızı gerçekleştirebilirsiniz.    ",
    height: "18",
    capacity: "20",
    food: "16",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/7/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/7/1.jpeg",
      "/images/yachts/motoryatlar/7/2.jpeg",
      "/images/yachts/motoryatlar/7/3.jpeg",
      "/images/yachts/motoryatlar/7/4.jpeg",
      "/images/yachts/motoryatlar/7/5.jpeg",
      "/images/yachts/motoryatlar/7/6.jpeg",
      "/images/yachts/motoryatlar/7/7.jpeg",
      "/images/yachts/motoryatlar/7/8.jpeg",
    ],
  },
  {
    id: "8",
    type: "motoryacht",
    description:
      "20 kişi kapasiteye sahip bu yatımız ile doğum günü,bekarlığa veda gibi organizasyonlarınızı gerçekleştirebilirsiniz.Şatafat tutkunları için bir numaralı seçenek olmaktadır.",
    height: "23",
    capacity: "20",
    food: "15",
    crew: "3",
    CardImage: "/images/yachts/motoryatlar/8/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/8/1.jpeg",
      "/images/yachts/motoryatlar/8/2.jpeg",
      "/images/yachts/motoryatlar/8/3.jpeg",
      "/images/yachts/motoryatlar/8/4.jpeg",
      "/images/yachts/motoryatlar/8/5.jpeg",
      "/images/yachts/motoryatlar/8/6.jpeg",
      "/images/yachts/motoryatlar/8/7.jpeg",
      "/images/yachts/motoryatlar/8/8.jpeg",
      "/images/yachts/motoryatlar/8/9.jpeg",
    ],
  },
  {
    id: "9",
    type: "motoryacht",
    description:
      "Keyifli anlara ev sahipliği yapan bu yatımız ile 15 kişiye kadar yat kiralama hizmeti verilmektedir.Geniş arka havuzu ile kalabalık akşam yemekleri için ideal bir seçimdir.",
    height: "16",
    capacity: "16",
    food: "12",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/9/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/9/1.jpeg",
      "/images/yachts/motoryatlar/9/2.jpeg",
      "/images/yachts/motoryatlar/9/3.jpeg",
      "/images/yachts/motoryatlar/9/4.jpeg",
      "/images/yachts/motoryatlar/9/5.jpeg",
      "/images/yachts/motoryatlar/9/6.jpeg",
    ],
  },
  {
    id: "10",
    type: "motoryacht",
    description:
      "Hem güzel,hem ekonomik bir yat arıyor iseniz doğru adrestesiniz.10 kişiye kadar yat kiralama hizmeti verebildiğimiz bu yatımız ile eğlenceyi doruklarda yaşayın.",
    height: "17",
    capacity: "10",
    food: "8",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/10/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/10/1.jpeg",
      "/images/yachts/motoryatlar/10/2.jpeg",
      "/images/yachts/motoryatlar/10/3.jpeg",
      "/images/yachts/motoryatlar/10/4.jpeg",
      "/images/yachts/motoryatlar/10/5.jpeg",
    ],
  },
  {
    id: "11",
    type: "motoryacht",
    description:
      "12 kişi kapasiteye sahip özel yapım yatımız ile her türlü organizasyonunuzu gerçekleştirebilirsiniz.",
    height: "15",
    capacity: "12",
    food: "8",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/11/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/11/1.jpeg",
      "/images/yachts/motoryatlar/11/2.jpeg",
      "/images/yachts/motoryatlar/11/3.jpeg",
      "/images/yachts/motoryatlar/11/4.jpeg",
      "/images/yachts/motoryatlar/11/5.jpeg",
      "/images/yachts/motoryatlar/11/6.jpeg",
    ],
  },
  {
    id: "12",
    type: "motoryacht",
    CardImage: "/images/motoryatlar/12/1.jpeg",
    description:
      "36 kişi kapasiteli bu yatımız ile ev konforunu İstanbul Boğazı'na taşıyabilirsiniz.Her detayın özenle planlandığı bu yatımızda her türlü organizasyonunuzu gerçekleştirebilirsiniz.",
    height: "18",
    capacity: "10",
    food: "6",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/12/1.jpg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/motoryatlar/12/1.jpg",
      "/images/yachts/motoryatlar/12/2.jpg",
      "/images/yachts/motoryatlar/12/3.jpg",
      "/images/yachts/motoryatlar/12/4.jpg",
      "/images/yachts/motoryatlar/12/5.jpg",
      "/images/yachts/motoryatlar/12/6.jpg",
      "/images/yachts/motoryatlar/12/7.jpg",
      "/images/yachts/motoryatlar/12/8.jpg",
    ],
  },
  {
    id: "13",
    type: "invite-yacht",
    description:
      "Şık görünümü ile misafirlerimizin en çok tercih ettiği yatlarımızdan biri olan bu yatımızda yemek düzeninde 60,kokteyl düzeninde 80 kişiye kadar hizmet verilebilmektedir.Davet organizasyonlarınız içim ideal bir seçimdir.",
    height: "24",
    capacity: "80",
    food: "60",
    crew: "6",
    CardImage: "/images/yachts/davet-tekneleri/1/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/davet-tekneleri/1/1.jpeg",
      "/images/yachts/davet-tekneleri/1/2.jpeg",
      "/images/yachts/davet-tekneleri/1/3.jpeg",
      "/images/yachts/davet-tekneleri/1/4.jpeg",
      "/images/yachts/davet-tekneleri/1/5.jpeg",
      "/images/yachts/davet-tekneleri/1/6.jpeg",
      "/images/yachts/davet-tekneleri/1/7.jpeg",
      "/images/yachts/davet-tekneleri/1/8.jpeg",
      "/images/yachts/davet-tekneleri/1/9.jpeg",
      "/images/yachts/davet-tekneleri/1/10.jpeg",
    ],
  },
  {
    id: "14",
    type: "invite-yacht",
    description:
      "Modern ve farklı rengi ile dikkatleri üzerine çeken bu yatımızın iç dekorasyonunda da bu modern mimariyi görebilmektesiniz.Yemek düzeninde 70,kokteyl düzeninde 100 kişiye kadar hizmet verilebilmektedir.",
    height: "28",
    capacity: "100",
    food: "70",
    crew: "6",
    CardImage: "/images/yachts/davet-tekneleri/2/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/davet-tekneleri/2/1.jpeg",
      "/images/yachts/davet-tekneleri/2/1.jpeg",
      "/images/yachts/davet-tekneleri/2/1.jpeg",
      "/images/yachts/davet-tekneleri/2/1.jpeg",
      "/images/yachts/davet-tekneleri/2/1.jpeg",
      "/images/yachts/davet-tekneleri/2/1.jpeg",
    ],
  },
  {
    id: "15",
    type: "invite-yacht",
    description:
      "Kurumsal organizasyonlar için en ideal seçimlerden biri olan bu teknemiz geniş ve modern salonu ile ön plana çıkmaktadır.80 kişiye kadar hizmet verilmektedir.",
    height: "26",
    capacity: "80",
    food: "60",
    crew: "5",
    CardImage: "/images/yachts/davet-tekneleri/3/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/davet-tekneleri/3/1.jpeg",
      "/images/yachts/davet-tekneleri/3/2.jpeg",
      "/images/yachts/davet-tekneleri/3/3.jpeg",
      "/images/yachts/davet-tekneleri/3/4.jpeg",
      "/images/yachts/davet-tekneleri/3/5.jpeg",
      "/images/yachts/davet-tekneleri/3/6.jpeg",
      "/images/yachts/davet-tekneleri/3/7.jpeg",
      "/images/yachts/davet-tekneleri/3/8.jpeg",
    ],
  },
  {
    id: "16",
    type: "invite-yacht",
    description:
      "42 metre uzunluğundaki bu teknemiz modern ve şık görünümü tüm dikkatleri üzerine çekmektedir.Geniş salon hacmi ile birlikte 300 kişiye kadar yemekli organizasyonlar gerçekleştirilebilmektedir.",
    height: "42",
    capacity: "300",
    food: "300",
    crew: "12",
    CardImage: "/images/yachts/davet-tekneleri/4/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/davet-tekneleri/4/1.jpeg",
      "/images/yachts/davet-tekneleri/4/2.jpeg",
      "/images/yachts/davet-tekneleri/4/3.jpeg",
      "/images/yachts/davet-tekneleri/4/4.jpeg",
      "/images/yachts/davet-tekneleri/4/5.jpeg",
      "/images/yachts/davet-tekneleri/4/6.jpeg",
    ],
  },
  {
    id: "17",
    type: "invite-yacht",
    description:
      "500 kişiye kadar hizmet verilebilen bu teknemiz İstanbul Boğazı'nın en büyük ve modern teknelerinden biri konumundadır.",
    height: "50",
    capacity: "500",
    food: "500",
    crew: "15",
    CardImage: "/images/yachts/davet-tekneleri/5/1.jpeg",
    location: "İstanbul",
    DetailImages: [
      "/images/yachts/davet-tekneleri/5/1.jpeg",
      "/images/yachts/davet-tekneleri/5/2.jpeg",
      "/images/yachts/davet-tekneleri/5/3.jpeg",
      "/images/yachts/davet-tekneleri/5/4.jpeg",
      "/images/yachts/davet-tekneleri/5/5.jpeg",
      "/images/yachts/davet-tekneleri/5/6.jpeg",
      "/images/yachts/davet-tekneleri/5/7.jpeg",
      "/images/yachts/davet-tekneleri/5/8.jpeg",
    ],
  },
  {
    id: "18",
    type: "motoryacht",
    height: "17",
    capacity: "10",
    food: "10",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/18/1.jpg",
    location: "Muğla",
    DetailImages: [
      "/images/yachts/motoryatlar/18/1.jpg",
      "/images/yachts/motoryatlar/18/2.jpg",
      "/images/yachts/motoryatlar/18/3.jpg",
      "/images/yachts/motoryatlar/18/4.jpg",
      "/images/yachts/motoryatlar/18/5.jpg",
      "/images/yachts/motoryatlar/18/6.jpg",
      "/images/yachts/motoryatlar/18/7.jpg",
      "/images/yachts/motoryatlar/18/8.jpg",
      "/images/yachts/motoryatlar/18/9.jpg",
      "/images/yachts/motoryatlar/18/10.jpg",
      "/images/yachts/motoryatlar/18/11.jpg",
    ],
  },
  {
    id: "19",
    type: "motoryacht",
    height: "17",
    capacity: "10",
    food: "10",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/19/2.jpg",
    location: "Muğla",
    DetailImages: [
      "/images/yachts/motoryatlar/19/1.jpg",
      "/images/yachts/motoryatlar/19/2.jpg",
      "/images/yachts/motoryatlar/19/3.jpg",
      "/images/yachts/motoryatlar/19/4.jpg",
      "/images/yachts/motoryatlar/19/5.jpg",
      "/images/yachts/motoryatlar/19/6.jpg",
      "/images/yachts/motoryatlar/19/7.jpg",
      "/images/yachts/motoryatlar/19/8.jpg",
      "/images/yachts/motoryatlar/19/9.jpg",
      "/images/yachts/motoryatlar/19/10.jpg",
      "/images/yachts/motoryatlar/19/11.jpg",
      "/images/yachts/motoryatlar/19/12.jpg",
    ],
  },
  {
    id: "20",
    type: "motoryacht",
    height: "17",
    capacity: "10",
    food: "10",
    crew: "2",
    CardImage: "/images/yachts/motoryatlar/20/1.jpg",
    location: "Muğla",
    DetailImages: [
      "/images/yachts/motoryatlar/20/1.jpg",
      "/images/yachts/motoryatlar/20/2.jpg",
      "/images/yachts/motoryatlar/20/3.jpg",
      "/images/yachts/motoryatlar/20/4.jpg",
      "/images/yachts/motoryatlar/20/5.jpg",
      "/images/yachts/motoryatlar/20/6.jpg",
      "/images/yachts/motoryatlar/20/7.jpg",
      "/images/yachts/motoryatlar/20/8.jpg",
      "/images/yachts/motoryatlar/20/9.jpg",
      "/images/yachts/motoryatlar/20/10.jpg",
      "/images/yachts/motoryatlar/20/11.jpg",
      "/images/yachts/motoryatlar/20/12.jpg",
    ],
  },
];
